include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_return: error
    missing_required_param: error
    todo: warning

  exclude:
    - /**.g.dart

linter:
  rules:
    constant_identifier_names: false
    library_private_types_in_public_api: false
    use_key_in_widget_constructors: false
    unnecessary_string_escapes: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_specify_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_positional_boolean_parameters: true
    avoid_setters_without_getters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    directives_ordering: true
    join_return_with_assignment: true
    no_adjacent_strings_in_list: true
    parameter_assignments: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_setters_to_change_properties: true
    use_string_buffers: true

formatter:
  trailing_commas: preserve
