name: poe_shared
description: "Provides helper classes and mixins"
publish_to: 'none'
resolution: workspace
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  # base library functions
  game_tools_lib:
    path: ../../../plugins/game_tools_lib

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Asset file folders to be used in this and following packages!
  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/images/compare/
    - assets/areas/
    - assets/layouts/
