name: poe1_tools
description: "Project for Path of Exile 1"
publish_to: 'none'
resolution: workspace
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  # base library functions
  game_tools_lib:
    path: ../../../plugins/game_tools_lib

  # base shared functions
  poe_shared:
    path: ../poe_shared

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Asset file folders to be used in this and following packages! DONT USE SPACES
  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/images/compare/
    - assets/areas/
    - assets/layouts/
    - assets/layouts/Act_1/
    - assets/layouts/Act_1/The_Twilight_Strand/
    - assets/layouts/Act_1/The_Coast/
    - assets/layouts/Act_1/The_Tidal_Island/
    - assets/layouts/Act_1/The_Mud_Flats/
    - assets/layouts/Act_1/The_Submerged_Passage/
    - assets/layouts/Act_1/The_Flooded_Depths/
    - assets/layouts/Act_1/The_Ledge/
    - assets/layouts/Act_1/The_Climb/
    - assets/layouts/Act_1/The_Lower_Prison/
    - assets/layouts/Act_1/The_Upper_Prison/
    - assets/layouts/Act_1/Prisoner's_Gate/
    - assets/layouts/Act_1/The_Ship_Graveyard/
    - assets/layouts/Act_1/The_Ship_Graveyard_Cave/
    - assets/layouts/Act_1/The_Cavern_of_Wrath/
    - assets/layouts/Act_1/The_Cavern_of_Anger/
    - assets/layouts/Act_2/
    - assets/layouts/Act_2/The_Southern_Forest/
    - assets/layouts/Act_2/The_Old_Fields/
    - assets/layouts/Act_2/The_Crossroads/
    - assets/layouts/Act_2/The_Broken_Bridge/
    - assets/layouts/Act_2/The_Fellshrine_Ruins/
    - assets/layouts/Act_2/The_Crypt_Level_1/
    - assets/layouts/Act_2/The_Crypt_Level_2/
    - assets/layouts/Act_2/The_Chamber_of_Sins_Level_1/
    - assets/layouts/Act_2/The_Chamber_of_Sins_Level_2/
    - assets/layouts/Act_2/The_Riverways/
    - assets/layouts/Act_2/The_Western_Forest/
    - assets/layouts/Act_2/The_Weaver's_Chambers/
    - assets/layouts/Act_2/The_Wetlands/
    - assets/layouts/Act_2/The_Vaal_Ruins/
    - assets/layouts/Act_2/The_Northern_Forest/
    - assets/layouts/Act_2/The_Caverns/
    - assets/layouts/Act_2/The_Ancient_Pyramid/
    - assets/layouts/Act_3/
    - assets/layouts/Act_3/The_City_of_Sarn/
    - assets/layouts/Act_3/The_Slums/
    - assets/layouts/Act_3/The_Crematorium/
    - assets/layouts/Act_3/The_Sewers/
    - assets/layouts/Act_3/The_Marketplace/
    - assets/layouts/Act_3/The_Catacombs/
    - assets/layouts/Act_3/The_Battlefront/
    - assets/layouts/Act_3/The_Solaris_Temple_Level_1/
    - assets/layouts/Act_3/The_Solaris_Temple_Level_2/
    - assets/layouts/Act_3/The_Docks/
    - assets/layouts/Act_3/The_Ebony_Barracks/
    - assets/layouts/Act_3/The_Lunaris_Temple_Level_1/
    - assets/layouts/Act_3/The_Lunaris_Temple_Level_2/
    - assets/layouts/Act_3/The_Imperial_Gardens/
    - assets/layouts/Act_3/The_Library/
    - assets/layouts/Act_3/The_Archives/
    - assets/layouts/Act_3/The_Sceptre_of_God/
    - assets/layouts/Act_3/The_Upper_Sceptre_of_God/
    - assets/layouts/Act_4/
    - assets/layouts/Act_4/The_Aqueduct/
    - assets/layouts/Act_4/The_Dried_Lake/
    - assets/layouts/Act_4/The_Mines_Level_1/
    - assets/layouts/Act_4/The_Mines_Level_2/
    - assets/layouts/Act_4/The_Crystal_Veins/
    - assets/layouts/Act_4/Kaom's_Dream/
    - assets/layouts/Act_4/Kaom's_Stronghold/
    - assets/layouts/Act_4/Daresso's_Dream/
    - assets/layouts/Act_4/The_Grand_Arena/
    - assets/layouts/Act_4/The_Belly_of_the_Beast_Level_1/
    - assets/layouts/Act_4/The_Belly_of_the_Beast_Level_2/
    - assets/layouts/Act_4/The_Harvest/
    - assets/layouts/Act_4/The_Ascent/
    - assets/layouts/Act_5/
    - assets/layouts/Act_5/The_Slave_Pens/
    - assets/layouts/Act_5/The_Control_Blocks/
    - assets/layouts/Act_5/The_Templar_Courts/
    - assets/layouts/Act_5/The_Chamber_of_Innocence/
    - assets/layouts/Act_5/The_Torched_Courts/
    - assets/layouts/Act_5/The_Ruined_Square/
    - assets/layouts/Act_5/The_Reliquary/
    - assets/layouts/Act_5/The_Ossuary/
    - assets/layouts/Act_5/The_Cathedral_Rooftop/
    - assets/layouts/Act_6/
    - assets/layouts/Act_6/The_Twilight_Strand/
    - assets/layouts/Act_6/The_Coast/
    - assets/layouts/Act_6/The_Tidal_Island/
    - assets/layouts/Act_6/The_Mud_Flats/
    - assets/layouts/Act_6/The_Karui_Fortress/
    - assets/layouts/Act_6/The_Ridge/
    - assets/layouts/Act_6/The_Lower_Prison/
    - assets/layouts/Act_6/Shavronne's_Tower/
    - assets/layouts/Act_6/Prisoner's_Gate/
    - assets/layouts/Act_6/The_Western_Forest/
    - assets/layouts/Act_6/The_Riverways/
    - assets/layouts/Act_6/The_Wetlands/
    - assets/layouts/Act_6/The_Southern_Forest/
    - assets/layouts/Act_6/The_Cavern_of_Anger/
    - assets/layouts/Act_6/The_Beacon/
    - assets/layouts/Act_6/The_Brine_King's_Reef/
    - assets/layouts/Act_7/
    - assets/layouts/Act_7/The_Broken_Bridge/
    - assets/layouts/Act_7/The_Crossroads/
    - assets/layouts/Act_7/The_Fellshrine_Ruins/
    - assets/layouts/Act_7/The_Crypt/
    - assets/layouts/Act_7/The_Chamber_of_Sins_Level_1/
    - assets/layouts/Act_7/The_Chamber_of_Sins_Level_2/
    - assets/layouts/Act_7/The_Den/
    - assets/layouts/Act_7/The_Ashen_Fields/
    - assets/layouts/Act_7/The_Northern_Forest/
    - assets/layouts/Act_7/The_Causeway/
    - assets/layouts/Act_7/The_Vaal_City/
    - assets/layouts/Act_7/The_Temple_of_Decay_Level_1/
    - assets/layouts/Act_7/The_Temple_of_Decay_Level_2/
    - assets/layouts/Act_8/
    - assets/layouts/Act_8/The_Sarn_Ramparts/
    - assets/layouts/Act_8/The_Toxic_Conduits/
    - assets/layouts/Act_8/Doedre's_Cesspool/
    - assets/layouts/Act_8/The_Quay/
    - assets/layouts/Act_8/The_Grain_Gate/
    - assets/layouts/Act_8/The_Hidden_Underbelly/
    - assets/layouts/Act_8/The_Solaris_Concourse/
    - assets/layouts/Act_8/The_Solaris_Temple_Level_1/
    - assets/layouts/Act_8/The_Solaris_Temple_Level_2/
    - assets/layouts/Act_8/The_Harbour_Bridge/
    - assets/layouts/Act_8/The_Bath_House/
    - assets/layouts/Act_8/The_High_Gardens/
    - assets/layouts/Act_8/The_Lunaris_Concourse/
    - assets/layouts/Act_8/The_Lunaris_Temple_Level_1/
    - assets/layouts/Act_8/The_Lunaris_Temple_Level_2/
    - assets/layouts/Act_9/
    - assets/layouts/Act_9/The_Blood_Aqueduct/
    - assets/layouts/Act_9/The_Descent/
    - assets/layouts/Act_9/The_Vastiri_Desert/
    - assets/layouts/Act_9/The_Oasis/
    - assets/layouts/Act_9/The_Foothills/
    - assets/layouts/Act_9/The_Boiling_Lake/
    - assets/layouts/Act_9/The_Tunnel/
    - assets/layouts/Act_9/The_Quarry/
    - assets/layouts/Act_9/The_Belly_of_the_Beast/
    - assets/layouts/Act_9/The_Rotting_Core/
    - assets/layouts/Act_10/
    - assets/layouts/Act_10/The_Cathedral_Rooftop/
    - assets/layouts/Act_10/The_Ravaged_Square/
    - assets/layouts/Act_10/The_Control_Blocks/
    - assets/layouts/Act_10/The_Ossuary/
    - assets/layouts/Act_10/The_Torched_Courts/
    - assets/layouts/Act_10/The_Desecrated_Chambers/
    - assets/layouts/Act_10/The_Canals/
    - assets/layouts/Act_10/The_Feeding_Trough/